package com.duan1.components;

import com.duan1.DAO.HoaDonChiTietDAO;
import com.duan1.DAO.HoaDonDAO;
import com.duan1.DAO.KhachHangDAO;
import com.duan1.DAO.NhanVienDAO;
import com.duan1.DAO.SanPhamDAO;
import com.duan1.Entity.HoaDon;
import com.duan1.Entity.HoaDonChiTiet;
import com.duan1.Entity.KhachHang;
import com.duan1.Entity.NhanVien;
import com.duan1.Entity.SanPham;
import com.duan1.Helper.Msgbox;
import com.duan1.swing.ScrollBarCustom;
import com.duan1.ui.MainJFrame;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.text.ParseException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class JDL_ThongTinChiTiet_LSHoaDon extends javax.swing.JDialog {

    HoaDonDAO daoHD = new HoaDonDAO();
    SanPhamDAO daoSP = new SanPhamDAO();
    NhanVienDAO daoNV = new NhanVienDAO();
    HoaDonChiTietDAO daoCT = new HoaDonChiTietDAO();
    KhachHangDAO daoKH = new KhachHangDAO();
    MainJFrame m = new MainJFrame();
    List<HoaDonChiTiet> listCT = daoCT.selectAll();
    List<HoaDon> listHD = daoHD.selectAll();
    int index;

    public JDL_ThongTinChiTiet_LSHoaDon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //dulieu();
        init();
        this.setBackground(new Color(0,0,0,0));
        initMoving(this);
    }

    public void setFrom(HoaDon hd) throws ParseException {
        NhanVien nv = daoNV.selectByid(hd.getMaNV());
        KhachHang kh = daoKH.selectByid(hd.getMaKH());

        lblHoaDon.setText(hd.getMaHD());
        lblNgay.setText(hd.getNgayTao() + "");
        lblNhanVien.setText(nv.getTenNV());
        lblkhachhang.setText(kh.getTenKH());

    }

    public void display(int index) throws ParseException {
        HoaDon hd = listHD.get(index);
        setFrom(hd);

    }

    public void dulieu(String maHoaDon) {
        //List<HoaDonChiTiet> listCT = (List<HoaDonChiTiet>) daoCT.selectByid(HoaDon);
        DefaultTableModel model = (DefaultTableModel) tblCHITIET.getModel();
        model.setRowCount(0);

        try {

            // HoaDon hd = daoHD.selectByid(HoaDon);
            //  HoaDonChiTiet ct = daoCT.selectByid(HoaDon);        
            listCT = daoCT.selectByKeyword(maHoaDon);
            long tongTien = daoCT.getTongTien(maHoaDon);
            lblTongTien.setText("" + tongTien);
            for (HoaDonChiTiet ct : listCT) {

                SanPham sp = daoSP.selectByid(ct.getMaSP());
                Object[] row = {
                    sp.getMaSP(),
                    sp.getTenSP(),
                    ct.getSoLuong(),
                    sp.getDonGia(),
                    ct.getThanhTien()

                };

                model.addRow(row);
                model.fireTableDataChanged();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi load dữ liệu");

            e.printStackTrace();
        }
    }

    public void init() {
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
    }
     int x;
    int y;
     public void initMoving(JDL_ThongTinChiTiet_LSHoaDon l) {
        lblTTCT.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                x = evt.getX();
                y = evt.getY();
            }
        });
        lblTTCT.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                l.setLocation(e.getXOnScreen() - x, e.getYOnScreen() - y);
            }

        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrang1 = new com.duan1.components.panelTrang();
        lblTTCT = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblkhachhang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCHITIET = new com.duan1.swing.Table();
        lblThoat1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        panelTrang1.setBackground(new java.awt.Color(204, 102, 255));

        lblTTCT.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTTCT.setText("THÔNG TIN CHI TIẾT ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Mã hóa đơn:");

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblHoaDon.setText("hd");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Nhân viên:");

        lblNhanVien.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblNhanVien.setText("hd");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Ngày:");

        lblNgay.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblNgay.setText("hd");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("Khách hàng:");

        lblkhachhang.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblkhachhang.setText("hd");

        jScrollPane1.setBorder(null);

        tblCHITIET.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá ", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCHITIET);

        lblThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/close1.png"))); // NOI18N
        lblThoat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoat1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThoat1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThoat1MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setText("Tổng Tiền:");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongTien.setText("0");

        javax.swing.GroupLayout panelTrang1Layout = new javax.swing.GroupLayout(panelTrang1);
        panelTrang1.setLayout(panelTrang1Layout);
        panelTrang1Layout.setHorizontalGroup(
            panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrang1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTrang1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTTCT, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblThoat1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTrang1Layout.createSequentialGroup()
                        .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTrang1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrang1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTrang1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrang1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrang1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        panelTrang1Layout.setVerticalGroup(
            panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrang1Layout.createSequentialGroup()
                .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrang1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTTCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTrang1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblThoat1)))
                .addGap(18, 18, 18)
                .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrang1Layout.createSequentialGroup()
                        .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblHoaDon))
                        .addGap(18, 18, 18)
                        .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblNhanVien)))
                    .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelTrang1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(lblNgay)))
                        .addGroup(panelTrang1Layout.createSequentialGroup()
                            .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(lblkhachhang))
                            .addGap(43, 43, 43))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblTongTien))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoat1MouseClicked
       dispose();
    }//GEN-LAST:event_lblThoat1MouseClicked

    private void lblThoat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoat1MouseEntered
       lblThoat1.setBackground(Color.red);
       lblThoat1.setOpaque(true);
    }//GEN-LAST:event_lblThoat1MouseEntered

    private void lblThoat1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoat1MouseExited
         lblThoat1.setBackground(Color.white);
       lblThoat1.setOpaque(true);
    }//GEN-LAST:event_lblThoat1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDL_ThongTinChiTiet_LSHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDL_ThongTinChiTiet_LSHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDL_ThongTinChiTiet_LSHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDL_ThongTinChiTiet_LSHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDL_ThongTinChiTiet_LSHoaDon dialog = new JDL_ThongTinChiTiet_LSHoaDon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblTTCT;
    private javax.swing.JLabel lblThoat1;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblkhachhang;
    private com.duan1.components.panelTrang panelTrang1;
    private com.duan1.swing.Table tblCHITIET;
    // End of variables declaration//GEN-END:variables

}
