CREATE DATABASE QL_PhuKienQuaTang
GO

USE QL_PhuKienQuaTang
GO

---- TẠO BẢNG

-- 1.Bảng Tài Khoản
CREATE TABLE TaiKhoan(
	MaTK INT IDENTITY(1,1),
	TenTK VARCHAR(20) NOT NULL,
	MatKhau VARCHAR(20) NOT NULL,
	ChucVu BIT NOT NULL,
	TrangThai BIT NOT NULL
);
GO

-- 2.Bảng Nhân Viên
CREATE TABLE NhanVien(
	MaNV VARCHAR(15) NOT NULL,
	MaTK INT NOT NULL,
	TenNV NVARCHAR(50) NOT NULL,
	GioiTinh BIT NOT NULL,
	CCCD VARCHAR(13) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	HinhAnh VARCHAR(200) NOT NULL,
	GhiChu NVARCHAR(200) ,
	TrangThai BIT NOT NULL
);
GO

-- 3.Bảng Danh Mục

CREATE TABLE DanhMuc(
	MaDM INT IDENTITY(1,1),
	TenDM NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE DonViTinh(
	MaDVT INT IDENTITY(1,1),
	TenDVT NVARCHAR(50) NOT NULL,
);

GO 
-- 4.Bảng Sản Phẩm

CREATE TABLE SanPham(
	MaSP VARCHAR(15) NOT NULL,
	MaVach VARCHAR(15) NOT NULL,
	MaDM INT NOT NULL,
	MaDVT INT NOT NULL,
	TenSP NVARCHAR(10) NOT NULL,
	SoLuongTonKho INT NOT NULL,
	HinhAnh NVARCHAR(200) NOT NULL,
	TrangThai NVARCHAR(50) NOT NULL
);
GO

-- 5.Bảng Khách Hàng

CREATE TABLE KhachHang (
	MaKH VARCHAR(15) NOT NULL,
	TenKH NVARCHAR(200) NOT NULL,
	SDT VARCHAR(11),
	DiemTichLuy INT 
);
GO

-- 6. Bảng Phiếu Nhập Kho

CREATE TABLE PhieuNhap (
	MaPN VARCHAR(15) NOT NULL,
	MaNV VARCHAR(15) NOT NULL,
	NgayNhap DATETIME NOT NULL,
	GhiChu NVARCHAR(200),
);
GO

-- 7. Bảng Phiếu Nhập Chi Tiết

CREATE TABLE PhieuNhapChiTiet(
	MaPNCT INT IDENTITY(1,1) NOT NULL,
	MaPN VARCHAR(15) NOT NULL,
	MaSP VARCHAR(15) NOT NULL,
	SoLuongNhap INT NOT NULL,
	GiaNhap FLOAT NOT NULL,
	GiaBan FLOAT NOT NULL
);
GO

-- 8. Bảng Hóa Đơn
CREATE TABLE HoaDon(
	MaHD VARCHAR(15) NOT NULL,
	MaKH VARCHAR(15) NOT NULL,
	MaNV VARCHAR(15) NOT NULL,
	NgayTao DATETIME NOT NULL,
	GhiChu NVARCHAR(200)
);
GO

-- 9. Bảng Hóa Đơn Chi Tiết
CREATE TABLE HoaDonChiTiet(
	MaHD VARCHAR(15) NOT NULL,
	MaPNCT INT NOT NULL,
	MaSP VARCHAR(15) NOT NULL,
	SoLuongBan INT NOT NULL
);
GO

-- 10. Bảng Đơn Hàng
CREATE TABLE DonHang(
	MaDH VARCHAR(15) NOT NULL,
	MaKH VARCHAR(15) NOT NULL,
	MaHD VARCHAR(15) NOT NULL,
	TenNN NVARCHAR(200) NOT NULL,
	SdtNN VARCHAR(11) NOT NULL,
	NgayGiao DATETIME NOT NULL,
	GhiChu NVARCHAR(200) NOT NULL
);
GO
-- TẠO KHÓA CHÍNH

-- 1
ALTER TABLE dbo.TaiKhoan
ADD CONSTRAINT PK_MaTK PRIMARY KEY(MaTK);
GO

-- 2
ALTER TABLE dbo.NhanVien
ADD CONSTRAINT PK_MaNV PRIMARY KEY(MaNV);
GO

-- 3
ALTER TABLE dbo.DanhMuc
ADD CONSTRAINT PK_MaDM PRIMARY KEY(MaDM);
GO

-- 4
ALTER TABLE dbo.DonViTinh 
ADD CONSTRAINT PK_MaDVT PRIMARY KEY(MaDVT);
GO 

-- 5
ALTER TABLE dbo.SanPham
ADD CONSTRAINT PK_MaSP PRIMARY KEY(MaSP);
GO

-- 6
ALTER TABLE dbo.KhachHang
ADD CONSTRAINT PK_MaKH PRIMARY KEY(MaKH);
GO

-- 7
ALTER TABLE dbo.PhieuNhap
ADD CONSTRAINT PK_MaPN PRIMARY KEY(MaPN);
GO

-- 8
ALTER TABLE dbo.HoaDon
ADD CONSTRAINT PK_MaHD PRIMARY KEY(MaHD);
GO

-- 9
ALTER TABLE dbo.DonHang
ADD CONSTRAINT PK_MaDH PRIMARY KEY(MaDH);
GO

ALTER TABLE dbo.PhieuNhapChiTiet
ADD CONSTRAINT PK_MaPNCT PRIMARY KEY(MaPNCT);
GO
--- TẠO KHÓA NGOẠI

-- 1. Nhân Viên vs Tài Khoản
ALTER TABLE dbo.NhanVien
ADD CONSTRAINT FK_NhanVien_TaiKhoan 
FOREIGN KEY(MaTK) REFERENCES dbo.TaiKhoan (MaTK) ON DELETE NO ACTION;
GO

-- 2. Hóa Đơn vs Nhân Viên
ALTER TABLE dbo.HoaDon
ADD CONSTRAINT FK_HoaDon_NhanVien
FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien (MaNV) ON DELETE NO ACTION ON UPDATE CASCADE;
GO

-- 3. Phiếu Nhập vs Nhân Viên
ALTER TABLE dbo.PhieuNhap
ADD CONSTRAINT FK_PhieuNhap_NhanVien
FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien (MaNV) ON DELETE NO ACTION;
GO

-- 4. Sản Phẩm vs Danh Mục
ALTER TABLE dbo.SanPham
ADD CONSTRAINT FK_SanPham_DanhMuc
FOREIGN KEY (MaDM) REFERENCES dbo.DanhMuc (MaDM) ON DELETE NO ACTION;
GO 

-- 5. Sản Phẩm vs Đơn Vị Tính
ALTER TABLE dbo.SanPham
ADD CONSTRAINT FK_SanPhan_DonViTinh
FOREIGN KEY (MaDVT) REFERENCES dbo.DonViTinh(MaDVT) ON DELETE NO ACTION;
GO 

-- 6 . Hóa Đơn Chi Tiết vs Sản Phẩm
ALTER TABLE dbo.HoaDonChiTiet
ADD CONSTRAINT FK_HDCT_SanPham
FOREIGN KEY (MaSP) REFERENCES dbo.SanPham (MaSP) ON DELETE NO ACTION;
GO

-- 7. Hóa Đơn Chi Tiết vs Hóa Đơn
ALTER TABLE dbo.HoaDonChiTiet
ADD CONSTRAINT FK_HDCT_HoaDon
FOREIGN KEY (MaHD) REFERENCES  dbo.HoaDon (MaHD) ON DELETE NO ACTION;
GO

-- 8. Hóa Đơn vs Khách Hàng
ALTER TABLE dbo.HoaDon
ADD CONSTRAINT FK_HoaDon_KhachHang
FOREIGN KEY(MaKH) REFERENCES dbo.KhachHang(MaKH) ON DELETE NO ACTION;
GO

-- 9. Đơn Hàng vs Hóa Đơn
ALTER TABLE dbo.DonHang
ADD CONSTRAINT FK_DonHang_HoaDon
FOREIGN KEY (MaHD) REFERENCES dbo.HoaDon(MaHD) ON DELETE NO ACTION;
GO

-- 10. Phiếu Nhập Chi Tiết vs Sản Phẩm
ALTER TABLE dbo.PhieuNhapChiTiet
ADD CONSTRAINT FK_PNCT_SanPham
FOREIGN KEY (MaSP) REFERENCES dbo.SanPham(MaSP) ON DELETE NO ACTION ON UPDATE CASCADE;
GO

-- 11. PNCT vs Phiếu Nhập
ALTER TABLE dbo.PhieuNhapChiTiet
ADD CONSTRAINT FK_PNCT_PhieuNhap
FOREIGN KEY(MaPN) REFERENCES dbo.PhieuNhap(MaPN) ON DELETE NO ACTION;
GO

-- 12.  HDCT vs PNCT
ALTER TABLE dbo.HoaDonChiTiet
ADD CONSTRAINT FK_HDCT_PNCT
FOREIGN KEY (MaPNCT) REFERENCES dbo.PhieuNhapChiTiet(MaPNCT);
GO


--- TẠO KHÓA DUY NHẤT

-- 1. Bảng Nhân Viên
ALTER TABLE dbo.NhanVien
ADD CONSTRAINT UC_CCCD
UNIQUE(CCCD,SDT,MaTK)
GO

-- 2. Bảng Khách Hàng
ALTER TABLE dbo.KhachHang
ADD CONSTRAINT UC_KhachHang
UNIQUE (SDT)
GO

-- 3. Bảng Đơn Hàng
ALTER TABLE dbo.DonHang
ADD CONSTRAINT UC_DonHang
UNIQUE(MaHD)
GO 

-- Tạo dữ liệu

INSERT INTO dbo.TaiKhoan 
( TenTK, MatKhau, ChucVu, TrangThai ) 
VALUES 
('admin', 'admin123',  1,  0  ),
('staff', 'staff123',  0,  0  )
GO

